services:
  - type: web
    name: blackgift-ai
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: REDIS_URL
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS
        sync: false